name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/oppeypro
            git pull origin main

            # FRONTEND
            cd oppy-frontend
            npm install
            npm run build
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r build/* /usr/share/nginx/html/

            # BACKEND
            cd ../oppy-backend
            npm install
            if command -v pm2 &> /dev/null
            then
              pm2 restart server || pm2 start server.js --name server
            else
              pkill -f "node server.js" || true
              nohup node server.js > backend.log 2>&1 &
            fi
          EOF
